# Generated by Django 4.1.3 on 2022-11-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('D_Bug_Users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
